const express = require('express')
const { registerUser, loginUser, updateUser, getLoggedInUser, getUserProfilePhoto, updateUserProfilePhoto, getPublicUserByEmail, generateForgotPasswordCode, verifyForgotPasswordOTP, updateForgotPassword, deleteAccountPermanently, getFollowingAuthors, updateFollowingList, searchAuthors, getUserProfileById } = require('../controllers/userController')
const validateToken = require('../middlewares/validateToken')
const { getUserClockSettings, updateUserClockSettings } = require('../controllers/userClockController')
const router = express.Router()

router.route("/email/:email").get(getPublicUserByEmail)
router.route('/register').post(registerUser)
router.route('/login').post(loginUser)
router.route('/update').post(validateToken, updateUser)
router.route('/user').get(validateToken, getLoggedInUser).post(validateToken, getUserProfileById)
router.route('/profilePhoto').get(validateToken, getUserProfilePhoto).post(validateToken, updateUserProfilePhoto)
router.route('/forgotPassword/:email').get(generateForgotPasswordCode)
router.route('/verifyotp').post(verifyForgotPasswordOTP)
router.route('/updateForgotPassword').post(updateForgotPassword)
router.route('/deleteAccount').delete(validateToken, deleteAccountPermanently)
router.route('/clock').get(validateToken, getUserClockSettings).post(validateToken, updateUserClockSettings)
router.route('/following').get(validateToken, getFollowingAuthors).post(validateToken, updateFollowingList)
router.route('/search').post(validateToken, searchAuthors)

module.exports = router